"""init migration

Revision ID: 0ed2226ee94b
Revises: 
Create Date: 2025-10-05 15:53:21.160542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ed2226ee94b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('user', 'hr', 'admin', name='user_roles'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('cvs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('cv_title', sa.String(length=255), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('storage_path', sa.String(length=255), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('hr_user_id', sa.String(length=36), nullable=False),
    sa.Column('job_title', sa.String(length=255), nullable=True),
    sa.Column('job_location', sa.String(length=255), nullable=True),
    sa.Column('job_description', sa.Text(), nullable=True),
    sa.Column('min_experience', sa.Integer(), nullable=True),
    sa.Column('max_experience', sa.Integer(), nullable=True),
    sa.Column('degree_requirements', sa.String(length=100), nullable=True),
    sa.Column('requirements_json', sa.JSON(), nullable=True),
    sa.Column('skills_json', sa.JSON(), nullable=True),
    sa.Column('additional_info_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['hr_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analyses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cv_id', sa.String(length=36), nullable=False),
    sa.Column('job_description_text', sa.Text(), nullable=False),
    sa.Column('match_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ats_check_result_json', sa.JSON(), nullable=True),
    sa.Column('keyword_analysis_json', sa.JSON(), nullable=True),
    sa.Column('phrasing_suggestions_json', sa.JSON(), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cv_id'], ['cvs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('storage_path', sa.String(length=255), nullable=True),
    sa.Column('extracted_name', sa.String(length=255), nullable=True),
    sa.Column('extracted_email', sa.String(length=255), nullable=True),
    sa.Column('extracted_phone', sa.String(length=50), nullable=True),
    sa.Column('match_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('structured_profile_json', sa.JSON(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('processing', 'passed_filter', 'rejected', name='candidate_status'), nullable=True),
    sa.Column('rejection_reason', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generatedcvs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('original_cv_id', sa.String(length=36), nullable=False),
    sa.Column('template_name', sa.String(length=100), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=True),
    sa.Column('storage_path', sa.String(length=255), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['original_cv_id'], ['cvs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('generatedcvs')
    op.drop_table('candidates')
    op.drop_table('analyses')
    op.drop_table('jobs')
    op.drop_table('cvs')
    op.drop_table('users')
    # ### end Alembic commands ###
