"""Add candidate seeder

Revision ID: 4789a654ac6e
Revises: f794a4d166bb
Create Date: 2025-10-05 17:03:34.168526

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4789a654ac6e'
down_revision = 'f794a4d166bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('skills')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skills', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=True))

    # ### end Alembic commands ###
