"""Add total_experience to Candidate

Revision ID: 5589c4c19bc2
Revises: 87425c20d5c7
Create Date: 2025-11-16 00:17:40.486022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5589c4c19bc2'
down_revision = '87425c20d5c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_experience', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_column('total_experience')

    # ### end Alembic commands ###
