"""Add scoring_reason to Candidate model

Revision ID: 76d1094c8b31
Revises: 5589c4c19bc2
Create Date: 2025-11-17 13:41:50.901676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76d1094c8b31'
down_revision = '5589c4c19bc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scoring_reason', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_column('scoring_reason')

    # ### end Alembic commands ###
