"""adjust table to simplify candidate's skills management

Revision ID: 8307b90117bf
Revises: 711f28d88973
Create Date: 2025-11-13 17:00:47.374610

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8307b90117bf'
down_revision = '711f28d88973'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=50), nullable=True))
        batch_op.drop_column('extracted_name')
        batch_op.drop_column('extracted_email')
        batch_op.drop_column('structured_profile_json')
        batch_op.drop_column('extracted_phone')

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('skills_json')
        batch_op.drop_column('additional_info_json')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('additional_info_json', mysql.JSON(), nullable=True))
        batch_op.add_column(sa.Column('skills_json', mysql.JSON(), nullable=True))

    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extracted_phone', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('structured_profile_json', mysql.JSON(), nullable=True))
        batch_op.add_column(sa.Column('extracted_email', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('extracted_name', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('phone')
        batch_op.drop_column('email')
        batch_op.drop_column('name')

