"""added gpa column to candidate table

Revision ID: 87425c20d5c7
Revises: 8307b90117bf
Create Date: 2025-11-14 13:51:22.555336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87425c20d5c7'
down_revision = '8307b90117bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gpa', sa.Numeric(precision=5, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_column('gpa')

    # ### end Alembic commands ###
