"""add education and experience fields to candidate

Revision ID: 8bd14f33f89b
Revises: 4789a654ac6e
Create Date: 2025-10-10 16:19:55.097459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bd14f33f89b'
down_revision = '4789a654ac6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('education', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('experience', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_column('experience')
        batch_op.drop_column('education')

    # ### end Alembic commands ###
