"""empty message

Revision ID: c7be222a37c7
Revises: 4789a654ac6e
Create Date: 2025-10-07 17:39:48.524332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7be222a37c7'
down_revision = '4789a654ac6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min_gpa', sa.Numeric(precision=3, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('min_gpa')

    # ### end Alembic commands ###
